name: Continuous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run Build command
        run: npm run build
      - name: Run Unit tests
        run: npm run tests
